name       : ethtool
version    : '4.11'
release    : 5
source     :
    - https://www.kernel.org/pub/software/network/ethtool/ethtool-4.11.tar.xz : 12d8edaa8064966b8ef19cc44fecc096a68828035b6a1f2c67a27531a718e1b2
license    : GPL-2.0
component  : network.util
summary    : Utility for controlling network drivers and hardware
description: |
    Utility for controlling network drivers and hardware
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
