name       : ethtool
version    : 4.6
release    : 1
source     :
    - https://www.kernel.org/pub/software/network/ethtool/ethtool-4.6.tar.xz : e90589a9349d008cce8c0510ac4e8878efdc0ddb1b732a9a4cc333b101313415
license    : GPL-2.0
component  : network.util
summary    : Utility for controlling network drivers and hardware
description: |
    Utility for controlling network drivers and hardware
setup      : |
    %configure
check      : |
    %make check
build      : |
    %make
install    : |
    %make_install
