name       : ethtool
version    : '4.8'
release    : 2
source     :
    - https://www.kernel.org/pub/software/network/ethtool/ethtool-4.8.tar.xz : 403dfe288e2d8031eab0be3f5d0ca9128e120d61c52c3dc434474fa026eb4a43
license    : GPL-2.0
component  : network.util
summary    : Utility for controlling network drivers and hardware
description: |
    Utility for controlling network drivers and hardware
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
