name       : ethtool
version    : '4.19'
release    : 8
source     :
    - https://mirrors.edge.kernel.org/pub/software/network/ethtool/ethtool-4.19.tar.xz : b18a6c364e42c29cdac057cf183c9674163db96b30848adfa8c2a90450f6d0c8
license    : GPL-2.0-only
component  : network.util
summary    : Utility for controlling network drivers and hardware
description: |
    Utility for controlling network drivers and hardware
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
