name       : ethtool
version    : 5.0
release    : 9
source     :
    - https://mirrors.edge.kernel.org/pub/software/network/ethtool/ethtool-5.0.tar.xz : ecd4233bf023589125d53a4f4a9af19147a2dd8999f72c7768b1d500809bee99
license    : GPL-2.0-only
component  : network.util
summary    : Utility for controlling network drivers and hardware
description: |
    Utility for controlling network drivers and hardware
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
