name       : ethtool
version    : 4.17
release    : 7
source     :
    - https://mirrors.edge.kernel.org/pub/software/network/ethtool/ethtool-4.17.tar.xz : c46b1eb417c78793dddb3247b89eb8f50f6e398e12ee4670b092b3570728c585
license    : GPL-2.0-only
component  : network.util
summary    : Utility for controlling network drivers and hardware
description: |
    Utility for controlling network drivers and hardware
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
