name       : ethtool
version    : 4.10
release    : 3
source     :
    - https://www.kernel.org/pub/software/network/ethtool/ethtool-4.10.tar.xz : f0009726ecf34128b9a8238b71a652847dbc06bd1b877656699b0592b95c74ba
license    : GPL-2.0
component  : network.util
summary    : Utility for controlling network drivers and hardware
description: |
    Utility for controlling network drivers and hardware
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
